"use client";
import { RefreshCw, FileText, Upload } from "lucide-react";
import { useState } from "react";
import type { PatientDocumentTimelineItem } from "@wonflow/mock-data";
import type { PatientDocumentScreenModel } from "./patient-document-model";
import type { PatientDocumentUploadTransport } from "./resumable-patient-document-upload";
import { PatientDocumentRequestList } from "./patient-document-request-list";
import { PatientDocumentTimeline } from "./patient-document-timeline";
import { PatientDocumentUploader } from "./patient-document-uploader";
interface Props { initialModel:PatientDocumentScreenModel;transport:PatientDocumentUploadTransport;refresh():Promise<PatientDocumentScreenModel>;requestReadAccess(documentId:string):Promise<{accessToken:string}> }
export function PatientDocumentsScreen({initialModel,transport,refresh,requestReadAccess}:Props){const [model,setModel]=useState(initialModel);const [selectedRequestId,setSelectedRequestId]=useState<string>();const [refreshing,setRefreshing]=useState(false);const [openingDocumentId,setOpeningDocumentId]=useState<string>();function addUploadedDocument(document:PatientDocumentTimelineItem){setModel((current)=>({...current,documents:[document,...current.documents],requests:current.requests.map((request)=>request.id===document.requestId?{...request,status:"fulfilled"}:request)}))}async function reload(){setRefreshing(true);try{setModel(await refresh())}finally{setRefreshing(false)}}async function openDocument(id:string){setOpeningDocumentId(id);try{const access=await requestReadAccess(id);window.location.assign(`/patient/documents/view/${encodeURIComponent(access.accessToken)}`)}finally{setOpeningDocumentId(undefined)}}return <main className="space-y-5" id="main-content"><header className="rounded-[1.75rem] bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-900 p-5 text-white sm:p-7"><div className="flex items-start gap-3"><FileText aria-hidden size={24}/><div><p className="text-[10px] font-black uppercase tracking-widest text-violet-200">Patient portal</p><h1 className="mt-1 text-2xl font-black">My documents</h1><p className="mt-2 text-sm font-semibold text-indigo-100">Upload health documents, respond to care-team requests and view documents released to you.</p></div></div><button className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-white/10 px-4 text-sm font-black" disabled={refreshing} onClick={()=>void reload()} type="button"><RefreshCw aria-hidden className={refreshing?"animate-spin":""} size={16}/>Refresh</button></header><PatientDocumentRequestList onFulfill={setSelectedRequestId} requests={model.requests}/><section><h2 className="mb-3 flex items-center gap-2 text-base font-black"><Upload aria-hidden size={18}/>Add a document</h2><PatientDocumentUploader actor={model.actor} initialRequestId={selectedRequestId} onUploaded={addUploadedDocument} policy={model.uploadPolicy} transport={transport}/></section><PatientDocumentTimeline documents={model.documents} onOpen={(id)=>void openDocument(id)} openingDocumentId={openingDocumentId}/></main>}
