import type { BeginPatientDocumentUploadResult,CompletePatientDocumentUploadInput,PatientDocumentActor,PatientDocumentTimelineItem,UploadPatientDocumentChunkInput } from "@wonflow/mock-data";
const PREFIX="wonflow.patient-document-upload.";
export interface PatientDocumentUploadMetadata { categoryCode:string;clinicalDate:string;requestId?:string }
export interface PatientDocumentUploadTransport { beginUpload(input:{actor:PatientDocumentActor;fileName:string;mimeType:string;sizeBytes:number;categoryCode:string;clinicalDate:string;requestId?:string;clientFingerprint:string},signal?:AbortSignal):Promise<BeginPatientDocumentUploadResult>;uploadChunk(input:UploadPatientDocumentChunkInput,bytes:Blob,signal?:AbortSignal):Promise<{nextChunkIndex:number;uploadedBytes:number;totalBytes:number}>;completeUpload(input:CompletePatientDocumentUploadInput,signal?:AbortSignal):Promise<PatientDocumentTimelineItem> }
export interface RunPatientDocumentUploadInput { file:File;actor:PatientDocumentActor;metadata:PatientDocumentUploadMetadata;transport:PatientDocumentUploadTransport;signal?:AbortSignal;onProgress?(progress:number):void }
interface Checkpoint {uploadId:string;nextChunkIndex:number;chunkSizeBytes:number;expiresAt:string}
async function digest(bytes:ArrayBuffer){const hash=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(hash)).map((value)=>value.toString(16).padStart(2,"0")).join("")}
export async function createPatientDocumentFingerprint(file:File){return digest(new TextEncoder().encode(`${file.size}:${file.lastModified}:${file.type}`).buffer)}
function read(key:string):Checkpoint|undefined {if(typeof window==="undefined")return;const raw=sessionStorage.getItem(PREFIX+key);if(!raw)return;try{const value=JSON.parse(raw) as Checkpoint;if(Date.parse(value.expiresAt)<=Date.now()){sessionStorage.removeItem(PREFIX+key);return}return value}catch{sessionStorage.removeItem(PREFIX+key);return}}
function write(key:string,value:Checkpoint){if(typeof window!=="undefined")sessionStorage.setItem(PREFIX+key,JSON.stringify(value))}
export async function runPatientDocumentUpload({file,actor,metadata,transport,signal,onProgress}:RunPatientDocumentUploadInput){const fingerprint=await createPatientDocumentFingerprint(file);let checkpoint=read(fingerprint);if(!checkpoint){const started=await transport.beginUpload({actor,fileName:file.name,mimeType:file.type,sizeBytes:file.size,...metadata,clientFingerprint:fingerprint},signal);checkpoint={...started};write(fingerprint,checkpoint)}const total=Math.ceil(file.size/checkpoint.chunkSizeBytes);for(let index=checkpoint.nextChunkIndex;index<total;index++){if(signal?.aborted)throw new DOMException("Upload cancelled.","AbortError");const offset=index*checkpoint.chunkSizeBytes;const chunk=file.slice(offset,Math.min(offset+checkpoint.chunkSizeBytes,file.size));const result=await transport.uploadChunk({actor,uploadId:checkpoint.uploadId,chunkIndex:index,offsetBytes:offset,chunkSizeBytes:chunk.size,chunkChecksum:await digest(await chunk.arrayBuffer())},chunk,signal);checkpoint={...checkpoint,nextChunkIndex:result.nextChunkIndex};write(fingerprint,checkpoint);onProgress?.(Math.min(100,Math.round(result.uploadedBytes/result.totalBytes*100)))}const document=await transport.completeUpload({actor,uploadId:checkpoint.uploadId,finalChecksum:await digest(await file.arrayBuffer())},signal);sessionStorage.removeItem(PREFIX+fingerprint);onProgress?.(100);return document}
