"use client";
import { useCallback, useEffect, useState } from "react";
interface Patient { id: string; patientNumber: string; givenName: string; middleName: string | null; familyName: string; documents: Array<{ id: string; title: string; category: string; status: string; createdAt: string }> }
export default function DoctorDocumentsPage() {
  const [patients, setPatients] = useState<Patient[]>([]); const [selected, setSelected] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/v1/doctor/documents", { cache: "no-store" }); const body = await response.json() as { patients?: Patient[]; error?: string }; if (!response.ok) throw new Error(body.error); setPatients(body.patients ?? []); setSelected((current) => current || body.patients?.[0]?.id || ""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Patient documents could not be loaded."); } }, []);
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const data = new FormData(event.currentTarget); data.set("patientId", selected); const response = await fetch("/api/v1/doctor/documents", { method: "POST", body: data }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error); event.currentTarget.reset(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "The report could not be released."); } finally { setBusy(false); } }
  const patient = patients.find((item) => item.id === selected);
  return <div className="space-y-5"><header className="rounded-3xl bg-gradient-to-r from-slate-950 via-indigo-950 to-violet-900 p-6 text-white"><p className="text-xs font-black uppercase tracking-[0.2em] text-violet-200">Clinical workspace</p><h1 className="mt-2 text-3xl font-black">Patient reports & documents</h1><p className="mt-2 text-sm text-indigo-100">Review patient uploads and release clinical reports to patients under your care.</p></header>{error ? <div className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div> : null}<form className="grid gap-3 rounded-3xl border bg-white p-5 md:grid-cols-2" onSubmit={(event) => void upload(event)}><label className="text-xs font-bold md:col-span-2">Assigned patient<select className="mt-1 w-full rounded-xl border px-3 py-2" onChange={(event) => setSelected(event.target.value)} required value={selected}><option value="">Select patient</option>{patients.map((item) => <option key={item.id} value={item.id}>{[item.givenName, item.middleName, item.familyName].filter(Boolean).join(" ")} · {item.patientNumber}</option>)}</select></label><input className="rounded-xl border px-3 py-2" name="title" placeholder="Report title" required /><select className="rounded-xl border px-3 py-2" name="category"><option value="CLINICAL_REPORT">Clinical report</option><option value="PRESCRIPTION">Prescription</option><option value="DISCHARGE_SUMMARY">Discharge summary</option><option value="REFERRAL">Referral</option><option value="PREVIOUS_MEDICAL_HISTORY">Previous medical history (patient-brought record)</option></select><input accept="application/pdf,image/jpeg,image/png,image/webp" capture="environment" className="rounded-xl border border-dashed p-4 md:col-span-2" name="file" required type="file" /><button className="rounded-xl bg-indigo-700 p-3 font-black text-white disabled:opacity-50 md:col-span-2" disabled={busy || !selected} type="submit">{busy ? "Releasing…" : "Upload & release to patient"}</button></form><section className="rounded-3xl border bg-white p-5"><h2 className="text-lg font-black">Patient document history</h2>{patient?.documents.length ? <div className="mt-3 space-y-2">{patient.documents.map((document) => <div className="rounded-xl bg-slate-50 p-3" key={document.id}><div className="font-bold">{document.title}</div><div className="text-xs text-slate-500">{document.category} · {document.status}</div></div>)}</div> : <p className="mt-4 rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">No documents for the selected patient.</p>}</section></div>;
}
