import{database}from"@wonflow/database";import{requireTenantContext}from"@wonflow/contracts";import type{WonFlowRequestContext}from"@wonflow/contracts";import{WonFlowApiError}from"@/server/http/route-handler";import{attachmentInclude,serializeAttachments}from"@/server/diagnostics/diagnostics-service";
export class PatientPortalService{private async resolvePatient(rc:WonFlowRequestContext){const context=requireTenantContext(rc),access=await database.patientAccess.findFirst({where:{identityId:context.identityId,isActive:true,patient:{tenantId:context.tenantId,status:"ACTIVE"}},include:{patient:true},orderBy:{isPrimary:"desc"}});if(!access)throw new WonFlowApiError(403,"patient-access-required","This account is not linked to an active patient record.");return{context,patient:access.patient};}
async getHome(rc:WonFlowRequestContext){const{context:c,patient}=await this.resolvePatient(rc),now=new Date();const[appointments,prescriptions,diagnosticOrders,documents,notifications,invoices]=await Promise.all([database.appointment.findMany({where:{tenantId:c.tenantId,patientId:patient.id,startsAt:{gte:now},status:{in:["PENDING","CONFIRMED","CHECKED_IN","IN_QUEUE"]}},include:{service:true,doctor:{include:{staffProfile:{include:{membership:true}}}},branch:true,queueEntry:true},orderBy:{startsAt:"asc"},take:10}),database.prescription.findMany({where:{tenantId:c.tenantId,patientId:patient.id,status:{in:["ACTIVE","PARTIALLY_DISPENSED","DISPENSED"]}},include:{items:{include:{medication:true}}},orderBy:{createdAt:"desc"},take:20}),database.diagnosticOrder.findMany({where:{tenantId:c.tenantId,patientId:patient.id,results:{some:{status:{in:["FINAL","AMENDED","CORRECTED"]},releasedAt:{not:null}}}},include:{results:{where:{status:{in:["FINAL","AMENDED","CORRECTED"]},releasedAt:{not:null}}},attachments:attachmentInclude},orderBy:{createdAt:"desc"},take:20}),database.documentRecord.findMany({where:{tenantId:c.tenantId,patientId:patient.id,status:"RELEASED"},orderBy:{releasedAt:"desc"},take:20}),database.notification.findMany({where:{tenantId:c.tenantId,patientId:patient.id},orderBy:{createdAt:"desc"},take:30}),
    // A DRAFT invoice is internal working state (billing may still be
    // assembling line items) and is never shown to the patient it is about,
    // mirroring the DRAFT-note rule below.
    database.invoice.findMany({where:{tenantId:c.tenantId,patientId:patient.id,status:{not:"DRAFT"}},include:{lines:true,payments:{orderBy:{createdAt:"desc"}}},orderBy:{createdAt:"desc"},take:20})]);return{patient,appointments,prescriptions,diagnosticOrders:diagnosticOrders.map(serializeAttachments),documents,notifications,invoices};}
/** Signed (countersigned, where required) clinical notes only — a DRAFT note is never visible to the patient it is about. */
async listClinicalNotes(rc:WonFlowRequestContext){const{context:c,patient}=await this.resolvePatient(rc);return database.encounterNote.findMany({where:{tenantId:c.tenantId,status:{in:["SIGNED","RELEASED","AMENDED"]},releasedAt:{not:null},encounter:{patientId:patient.id}},include:{encounter:{select:{id:true,reason:true,startedAt:true,doctor:{select:{staffProfile:{select:{membership:{select:{displayName:true}}}}}}}}},orderBy:{releasedAt:"desc"}});}
async cancelAppointment(rc:WonFlowRequestContext,id:string,reason:string){const{context:c,patient}=await this.resolvePatient(rc);if(!reason.trim())throw new WonFlowApiError(400,"cancellation-reason-required","Enter a cancellation reason.");const a=await database.appointment.findFirst({where:{id,tenantId:c.tenantId,patientId:patient.id,status:{in:["PENDING","CONFIRMED"]}}});
  if(!a){
    // A cross-patient (or bogus-id) attempt is audited even though the response never reveals which case it was.
    const exists=await database.appointment.findFirst({where:{id,tenantId:c.tenantId},select:{id:true}});
    if(exists)await database.auditEvent.create({data:{tenantId:c.tenantId,branchId:c.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"patient.appointment.access_denied",entityType:"appointment",entityId:id,severity:"WARNING",sourceApplication:c.sourceApplication}});
    throw new WonFlowApiError(404,"appointment-not-cancellable","The appointment cannot be cancelled.");
  }
  return database.$transaction(async tx=>{const updated=await tx.appointment.update({where:{id:a.id},data:{status:"CANCELLED",cancellationReason:reason.trim(),cancelledAt:new Date()}});await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId:a.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"patient.appointment.cancelled",entityType:"appointment",entityId:a.id,severity:"INFORMATION",reason:reason.trim(),sourceApplication:c.sourceApplication}});await tx.outboxEvent.create({data:{tenantId:c.tenantId,type:"appointment.cancelled",aggregateType:"appointment",aggregateId:a.id,payload:{appointmentId:a.id,patientId:patient.id}}});return updated;});}}
export const patientPortalService=new PatientPortalService();
