import{randomBytes}from"node:crypto";import{database}from"@wonflow/database";import{requireBranchId,requirePermission,requireTenantContext}from"@wonflow/contracts";import type{WonFlowRequestContext}from"@wonflow/contracts";import{WonFlowApiError}from"@/server/http/route-handler";import{checkDoctorBookable}from"@/server/scheduling/effective-availability";
const normalizeOptional=(v?:string)=>v?.trim().toLowerCase()||null;const patientNumber=()=>`P-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${randomBytes(3).toString("hex").toUpperCase()}`;
const diagnosticTypeOf=(category:string):"LABORATORY"|"RADIOLOGY"|null=>{const value=category.trim().toUpperCase().replace(/[^A-Z0-9]+/g,"_");if(value==="LABORATORY"||value==="PATHOLOGY")return"LABORATORY";if(value==="RADIOLOGY"||value==="IMAGING")return"RADIOLOGY";return null;};
export class ReceptionService{
async getCatalog(rc:WonFlowRequestContext){const c=requireTenantContext(rc);requirePermission(c,"appointments.read");const[branches,doctors,services]=await Promise.all([database.branch.findMany({where:{tenantId:c.tenantId,organizationId:c.organizationId,archivedAt:null,status:"ACTIVE"},orderBy:[{isMainBranch:"desc"},{name:"asc"}],select:{id:true,name:true}}),database.doctorProfile.findMany({where:{tenantId:c.tenantId,staffProfile:{status:"ACTIVE",membership:{organizationId:c.organizationId,archivedAt:null,status:{in:["ACTIVE","INVITED"]}}}},include:{staffProfile:{include:{membership:true}}},orderBy:{staffProfile:{membership:{displayName:"asc"}}}}),database.serviceDefinition.findMany({where:{tenantId:c.tenantId,isActive:true,OR:[{branchId:null},{branch:{organizationId:c.organizationId,archivedAt:null,status:"ACTIVE"}}]},orderBy:[{category:"asc"},{name:"asc"}]})]);return{branches,practitioners:doctors.map(doctor=>{const doctorServices=services.filter(service=>service.doctorId===doctor.id&&service.priceMinorUnits!==null);const normalFee=doctorServices[0]?.priceMinorUnits??0;return{id:doctor.id,displayName:doctor.staffProfile.membership.displayName,specialtyName:doctor.specialty??"Clinical practitioner",primaryBranchId:doctor.staffProfile.branchId??branches[0]?.id??"",consultationFee:normalFee/100,urgentConsultationFee:normalFee?normalFee*1.5/100:0};}),services:services.map(service=>({id:service.id,name:service.name,category:service.category,price:service.priceMinorUnits===null?0:service.priceMinorUnits/100,doctorId:service.doctorId,branchId:service.branchId,publiclyBookable:service.publiclyBookable}))};}
async getOverview(rc:WonFlowRequestContext,date:string){const c=requireTenantContext(rc);requirePermission(c,"appointments.read");const branchId=requireBranchId(c),start=new Date(`${date}T00:00:00.000Z`),end=new Date(`${date}T23:59:59.999Z`);const[appointments,queue,patientsToday]=await Promise.all([database.appointment.findMany({where:{tenantId:c.tenantId,branchId,startsAt:{gte:start,lte:end}},orderBy:{startsAt:"asc"}}),database.queueEntry.findMany({where:{tenantId:c.tenantId,queue:{branchId,queueDate:start}},include:{patient:true,appointment:true},orderBy:[{priority:"desc"},{tokenNumber:"asc"}]}),database.patient.count({where:{tenantId:c.tenantId,createdAt:{gte:start,lte:end}}})]);return{patientsToday,appointmentsToday:appointments.length,waitingCount:queue.filter(x=>x.status==="WAITING").length,checkedInCount:appointments.filter(x=>x.checkedInAt).length,appointments,queue};}
async searchPatients(rc:WonFlowRequestContext,query:string){const c=requireTenantContext(rc);requirePermission(c,"patients.read");const value=query.trim();if(!value)return[];return database.patient.findMany({where:{tenantId:c.tenantId,OR:[{patientNumber:{contains:value,mode:"insensitive"}},{givenName:{contains:value,mode:"insensitive"}},{familyName:{contains:value,mode:"insensitive"}},{normalizedPhone:{contains:value.toLowerCase()}},{normalizedEmail:{contains:value.toLowerCase()}},{identifiers:{some:{normalizedValue:{contains:value.toLowerCase()}}}}]},include:{identifiers:{select:{type:true,value:true,isPrimary:true}}},orderBy:[{familyName:"asc"},{givenName:"asc"}],take:50});}
/**
 * Removes a patient from the directory.
 *
 * Archives rather than deletes: appointments, encounters, invoices and
 * diagnostic orders reference the record, and a hospital may not erase a
 * clinical history. A patient with activity keeps it and simply leaves the
 * directory.
 */
async archivePatient(rc:WonFlowRequestContext,id:string){const c=requireTenantContext(rc);requirePermission(c,"patients.manage");
  const patient=await database.patient.findFirst({where:{id,tenantId:c.tenantId}});
  if(!patient)throw new WonFlowApiError(404,"patient-not-found","The patient could not be found.");
  if(patient.status==="ARCHIVED")return patient;
  return database.patient.update({where:{id:patient.id},data:{status:"ARCHIVED",archivedAt:new Date()}});}
/**
 * Places laboratory and radiology orders for a walk-in booked at reception.
 *
 * These have no clinical encounter — the patient has not seen a doctor yet —
 * so the orders are raised against the patient directly and appear on the
 * department worklists immediately.
 */
async createDiagnosticOrders(rc:WonFlowRequestContext,input:{patientId:string;serviceIds:string[];clinicalReason?:string;priority?:string}){
  // Placing a walk-in order is part of booking a visit, which is reception's
  // own capability; it is not the department's permission to read its worklist.
  const c=requireTenantContext(rc);requirePermission(c,"appointments.manage");
  const branchId=requireBranchId(c);
  if(!c.membershipId)throw new WonFlowApiError(403,"membership-required","A staff membership is required to place orders.");
  const patient=await database.patient.findFirst({where:{id:input.patientId,tenantId:c.tenantId}});
  if(!patient)throw new WonFlowApiError(404,"patient-not-found","The patient could not be found.");
  const services=await database.serviceDefinition.findMany({where:{id:{in:input.serviceIds},tenantId:c.tenantId,isActive:true}});
  const diagnostic=services.map(service=>({service,type:diagnosticTypeOf(service.category)})).filter((entry):entry is{service:typeof services[number];type:"LABORATORY"|"RADIOLOGY"}=>entry.type!==null);
  if(diagnostic.length===0)return[];
  const orderedAt=new Date();
  return database.$transaction(diagnostic.map(({service,type})=>database.diagnosticOrder.create({data:{tenantId:c.tenantId,branchId,patientId:patient.id,encounterId:null,orderedByMembershipId:c.membershipId!,type,status:"ORDERED",priority:input.priority??"routine",code:service.code,name:service.name,clinicalReason:input.clinicalReason?.trim()||null,orderedAt}})));
}
/** Recent patients for the tenant, for the patient directory listing. */
async listPatients(rc:WonFlowRequestContext,limit=200){const c=requireTenantContext(rc);requirePermission(c,"patients.read");return database.patient.findMany({where:{tenantId:c.tenantId,status:{not:"ARCHIVED"}},include:{identifiers:{select:{type:true,value:true,isPrimary:true}}},orderBy:{createdAt:"desc"},take:Math.min(Math.max(limit,1),500)});}
async registerPatient(rc:WonFlowRequestContext,input:{givenName:string;middleName?:string;familyName:string;dateOfBirth?:string;sex?:string;phone?:string;email?:string;address?:object;guardianData?:object;consentData?:object;identifiers?:{type:string;system:string;value:string;isPrimary?:boolean}[]}){const c=requireTenantContext(rc);requirePermission(c,"patients.manage");const normalizedPhone=normalizeOptional(input.phone),normalizedEmail=normalizeOptional(input.email),dateOfBirth=input.dateOfBirth?new Date(`${input.dateOfBirth}T00:00:00.000Z`):null;const possibleDuplicates=await database.patient.findMany({where:{tenantId:c.tenantId,OR:[...(normalizedPhone?[{normalizedPhone}]:[]),...(normalizedEmail?[{normalizedEmail}]:[]),{givenName:{equals:input.givenName.trim(),mode:"insensitive"},familyName:{equals:input.familyName.trim(),mode:"insensitive"},dateOfBirth}]},take:10});
    for(const identifier of input.identifiers??[]){const value=identifier.value.trim();if(!value)continue;const existing=await database.patientIdentifier.findFirst({where:{tenantId:c.tenantId,system:identifier.system.trim(),normalizedValue:value.toLowerCase()}});if(existing)throw new WonFlowApiError(409,"duplicate-identifier",`A patient with this ${identifier.type} number is already registered.`);}
    const patient=await database.$transaction(async tx=>{const p=await tx.patient.create({data:{tenantId:c.tenantId,patientNumber:patientNumber(),givenName:input.givenName.trim(),middleName:input.middleName?.trim()||null,familyName:input.familyName.trim(),dateOfBirth,sex:input.sex?.trim()||null,phone:input.phone?.trim()||null,normalizedPhone,email:input.email?.trim()||null,normalizedEmail,address:input.address,guardianData:input.guardianData,consentData:input.consentData,identifiers:{create:input.identifiers?.filter(i=>i.value.trim()).map(i=>({tenantId:c.tenantId,type:i.type.trim(),system:i.system.trim(),value:i.value.trim(),normalizedValue:i.value.trim().toLowerCase(),isPrimary:i.isPrimary??false}))??[]}}});await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId:c.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"patient.registered",entityType:"patient",entityId:p.id,severity:"INFORMATION",sourceApplication:c.sourceApplication}});return p;});return{patient,possibleDuplicates};}
async bookAppointment(rc:WonFlowRequestContext,input:{patientId:string;doctorId?:string;serviceId?:string;startsAt:string;endsAt:string;reason?:string;source:string;idempotencyKey:string}){
  const c=requireTenantContext(rc);requirePermission(c,"appointments.manage");
  const branchId=requireBranchId(c),startsAt=new Date(input.startsAt),endsAt=new Date(input.endsAt);
  if(!Number.isFinite(startsAt.getTime())||!Number.isFinite(endsAt.getTime())||endsAt<=startsAt)throw new WonFlowApiError(400,"invalid-appointment-time","The appointment time is invalid.");
  const old=await database.idempotencyRecord.findUnique({where:{tenantId_key_operation:{tenantId:c.tenantId,key:input.idempotencyKey,operation:"appointment.book"}}});
  if(old?.responsePayload&&typeof old.responsePayload==="object"&&"appointmentId"in old.responsePayload){const a=await database.appointment.findFirst({where:{id:String(old.responsePayload.appointmentId),tenantId:c.tenantId}});if(a)return a;}
  return database.$transaction(async tx=>{
    if(!await tx.patient.findFirst({where:{id:input.patientId,tenantId:c.tenantId,status:"ACTIVE"}}))throw new WonFlowApiError(404,"patient-not-found","The patient could not be found.");
    const service=input.serviceId?await tx.serviceDefinition.findFirst({where:{id:input.serviceId,tenantId:c.tenantId,isActive:true,OR:[{branchId:null},{branchId}]}}):null;
    if(input.serviceId&&!service)throw new WonFlowApiError(400,"invalid-appointment-service","The selected service is unavailable at this branch.");
    if(service?.doctorId&&input.doctorId&&service.doctorId!==input.doctorId)throw new WonFlowApiError(400,"service-doctor-mismatch","The selected consultation service belongs to another doctor.");
    const doctorId=input.doctorId??service?.doctorId??null;
    if(doctorId&&!await tx.doctorProfile.findFirst({where:{id:doctorId,tenantId:c.tenantId,staffProfile:{membership:{organizationId:c.organizationId}}}}))throw new WonFlowApiError(400,"invalid-appointment-doctor","The selected doctor is unavailable.");
    if(doctorId&&await tx.appointment.findFirst({where:{tenantId:c.tenantId,branchId,doctorId,status:{in:["PENDING","CONFIRMED","CHECKED_IN","IN_QUEUE","IN_PROGRESS"]},startsAt:{lt:endsAt},endsAt:{gt:startsAt}}}))throw new WonFlowApiError(409,"appointment-conflict","The selected clinician is no longer available at that time.");
    // Reception books against the doctor's sitting hours; the hospital roster
    // applies only on dates where the doctor has not recorded a sitting.
    if(doctorId){const branch=await tx.branch.findFirst({where:{id:branchId,tenantId:c.tenantId},select:{timezone:true}});const bookable=await checkDoctorBookable(tx,{tenantId:c.tenantId,doctorId,branchId,startsAt,endsAt,timezone:branch?.timezone??c.timezone});if(!bookable.ok)throw new WonFlowApiError(409,"doctor-unavailable",bookable.reason);}
    const a=await tx.appointment.create({data:{tenantId:c.tenantId,patientId:input.patientId,doctorId,branchId,serviceId:service?.id??null,consultationMode:service?.consultationMode??"IN_PERSON",status:"CONFIRMED",source:input.source,reason:input.reason?.trim()||null,startsAt,endsAt,idempotencyKey:input.idempotencyKey}});
    await tx.idempotencyRecord.create({data:{tenantId:c.tenantId,key:input.idempotencyKey,operation:"appointment.book",responsePayload:{appointmentId:a.id},expiresAt:new Date(Date.now()+86400000)}});
    await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"appointment.booked",entityType:"appointment",entityId:a.id,severity:"INFORMATION",sourceApplication:c.sourceApplication}});return a;
  });
}
async checkIn(rc:WonFlowRequestContext,id:string,input:{queueDate:string;priority?:number;notes?:string}){const c=requireTenantContext(rc);requirePermission(c,"queues.manage");const branchId=requireBranchId(c),queueDate=new Date(`${input.queueDate}T00:00:00.000Z`);return database.$transaction(async tx=>{const a=await tx.appointment.findFirst({where:{id,tenantId:c.tenantId,branchId,status:{in:["PENDING","CONFIRMED"]}}});if(!a)throw new WonFlowApiError(404,"appointment-not-found","The appointment cannot be checked in.");const q=await tx.queue.upsert({where:{tenantId_branchId_queueDate:{tenantId:c.tenantId,branchId,queueDate}},create:{tenantId:c.tenantId,branchId,queueDate},update:{}}),counter=await tx.queue.update({where:{id:q.id},data:{nextTokenNumber:{increment:1}}}),tokenNumber=counter.nextTokenNumber-1,queueEntry=await tx.queueEntry.create({data:{tenantId:c.tenantId,queueId:q.id,patientId:a.patientId,appointmentId:a.id,tokenNumber,priority:input.priority??0,notes:input.notes?.trim()||null},include:{patient:true,appointment:true}}),appointment=await tx.appointment.update({where:{id:a.id},data:{status:"IN_QUEUE",checkedInAt:new Date(),tokenNumber,queueStatus:"waiting"}});await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"appointment.checked-in",entityType:"appointment",entityId:a.id,severity:"INFORMATION",sourceApplication:c.sourceApplication}});return{appointment,queueEntry};});}
async cancelAppointment(rc:WonFlowRequestContext,id:string,reason:string){const c=requireTenantContext(rc);requirePermission(c,"appointments.manage");if(!reason.trim())throw new WonFlowApiError(400,"cancellation-reason-required","A cancellation reason is required.");return database.$transaction(async tx=>{const found=await tx.appointment.findFirst({where:{id,tenantId:c.tenantId,branchId:requireBranchId(c)}});if(!found)throw new WonFlowApiError(404,"appointment-not-found","The appointment could not be found.");const appointment=await tx.appointment.update({where:{id:found.id},data:{status:"CANCELLED",cancellationReason:reason.trim(),cancelledAt:new Date()}});await tx.queueEntry.updateMany({where:{tenantId:c.tenantId,appointmentId:id},data:{status:"CANCELLED",cancelledAt:new Date()}});await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId:c.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"appointment.cancelled",entityType:"appointment",entityId:id,severity:"INFORMATION",reason:reason.trim(),sourceApplication:c.sourceApplication}});return appointment;});}
}export const receptionService=new ReceptionService();
