import{database}from"@wonflow/database";import{requireBranchId,requirePermission,requireTenantContext}from"@wonflow/contracts";import type{WonFlowRequestContext}from"@wonflow/contracts";import{WonFlowApiError}from"@/server/http/route-handler";
export class DoctorService{private async resolveDoctor(rc:WonFlowRequestContext){const context=requireTenantContext(rc);if(!context.membershipId)throw new WonFlowApiError(403,"doctor-membership-required","A doctor membership is required.");const doctor=await database.doctorProfile.findFirst({where:{tenantId:context.tenantId,staffProfile:{membershipId:context.membershipId,status:"ACTIVE"}}});if(!doctor)throw new WonFlowApiError(403,"doctor-profile-required","A valid doctor profile is required.");return{context,doctor};}
async getDashboard(rc:WonFlowRequestContext,date:string){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"appointments.read");const appointments=await database.appointment.findMany({where:{tenantId:c.tenantId,branchId:requireBranchId(c),doctorId:doctor.id,startsAt:{gte:new Date(`${date}T00:00:00.000Z`),lte:new Date(`${date}T23:59:59.999Z`)}},include:{patient:true,queueEntry:true,service:true,encounter:true},orderBy:{startsAt:"asc"}});return{doctorId:doctor.id,appointments,metrics:{appointments:appointments.length,waiting:appointments.filter(a=>a.queueEntry?.status==="WAITING").length,inProgress:appointments.filter(a=>a.status==="IN_PROGRESS").length,completed:appointments.filter(a=>a.status==="COMPLETED").length}};}
private async getAppointmentDetail(tenantId:string,doctorId:string,appointmentId:string){const appointment=await database.appointment.findFirst({where:{id:appointmentId,tenantId,doctorId},include:{patient:true,queueEntry:true,service:true,encounter:true}});if(!appointment)throw new WonFlowApiError(404,"appointment-not-found","The appointment could not be found.");return appointment;}
/** Calls a waiting patient forward in the doctor's real queue. */
async callQueueEntry(rc:WonFlowRequestContext,appointmentId:string){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"queues.manage");const appointment=await this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);if(!appointment.queueEntry)throw new WonFlowApiError(409,"queue-entry-missing","This appointment has not been checked in to a queue.");if(appointment.queueEntry.status!=="WAITING")throw new WonFlowApiError(409,"queue-entry-not-waiting","Only a waiting patient can be called.");await database.queueEntry.update({where:{id:appointment.queueEntry.id},data:{status:"CALLED",calledAt:new Date()}});return this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);}
/** Returns a called or missed patient to the waiting line. */
async returnQueueEntry(rc:WonFlowRequestContext,appointmentId:string){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"queues.manage");const appointment=await this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);if(!appointment.queueEntry)throw new WonFlowApiError(409,"queue-entry-missing","This appointment has not been checked in to a queue.");await database.queueEntry.update({where:{id:appointment.queueEntry.id},data:{status:"WAITING",calledAt:null}});return this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);}
/** Marks a called patient as missed (no-show at the door). */
async skipQueueEntry(rc:WonFlowRequestContext,appointmentId:string){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"queues.manage");const appointment=await this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);if(!appointment.queueEntry)throw new WonFlowApiError(409,"queue-entry-missing","This appointment has not been checked in to a queue.");await database.queueEntry.update({where:{id:appointment.queueEntry.id},data:{status:"MISSED"}});return this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);}
/** Starts (or resumes) the clinical encounter for a called patient, opening the consultation. */
async startConsultation(rc:WonFlowRequestContext,appointmentId:string){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"encounters.manage");requirePermission(c,"queues.manage");const appointment=await this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);if(appointment.queueEntry?.status==="WAITING")throw new WonFlowApiError(409,"patient-not-called","Call the patient before starting the consultation.");const activeElsewhere=await database.appointment.findFirst({where:{tenantId:c.tenantId,doctorId:doctor.id,id:{not:appointmentId},status:"IN_PROGRESS"}});if(activeElsewhere)throw new WonFlowApiError(409,"another-consultation-active","Finish the current consultation before starting another.");const now=new Date();await database.$transaction(async tx=>{if(appointment.encounter&&appointment.encounter.status!=="CANCELLED"){await tx.encounter.update({where:{id:appointment.encounter.id},data:{status:"IN_PROGRESS",doctorId:doctor.id,startedAt:appointment.encounter.startedAt??now}});}else{await tx.encounter.create({data:{tenantId:c.tenantId,patientId:appointment.patientId,appointmentId:appointment.id,doctorId:doctor.id,branchId:appointment.branchId,status:"IN_PROGRESS",reason:appointment.reason,startedAt:now}});}if(appointment.queueEntry){await tx.queueEntry.update({where:{id:appointment.queueEntry.id},data:{status:"IN_SERVICE",startedAt:now}});}await tx.appointment.update({where:{id:appointment.id},data:{status:"IN_PROGRESS"}});});return this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);}
/** Completes the active clinical encounter and closes out the queue entry and appointment. */
async completeConsultation(rc:WonFlowRequestContext,appointmentId:string){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"encounters.manage");const appointment=await this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);if(!appointment.encounter)throw new WonFlowApiError(409,"encounter-not-found","No clinical encounter has been started for this appointment.");const now=new Date();await database.$transaction(async tx=>{await tx.encounter.update({where:{id:appointment.encounter!.id},data:{status:"COMPLETED",endedAt:now}});if(appointment.queueEntry){await tx.queueEntry.update({where:{id:appointment.queueEntry.id},data:{status:"COMPLETED",completedAt:now}});}await tx.appointment.update({where:{id:appointment.id},data:{status:"COMPLETED"}});});return this.getAppointmentDetail(c.tenantId,doctor.id,appointmentId);}
/** A doctor may reach an encounter as its treating clinician, or as the assigned supervisor of that clinician (to review and countersign). */
private async requireEncounterAccess(tenantId:string,doctorId:string,encounterId:string){const encounter=await database.encounter.findFirst({where:{id:encounterId,tenantId,OR:[{doctorId},{doctor:{supervisorDoctorId:doctorId}}]}});if(!encounter)throw new WonFlowApiError(404,"encounter-not-found","The encounter could not be found.");return encounter;}
async getEncounter(rc:WonFlowRequestContext,id:string){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"encounters.read");const encounter=await database.encounter.findFirst({where:{id,tenantId:c.tenantId,OR:[{doctorId:doctor.id},{doctor:{supervisorDoctorId:doctor.id}}]},include:{patient:{include:{identifiers:true,allergies:{where:{status:"ACTIVE"}},observations:{orderBy:{observedAt:"desc"},take:20}}},notes:{orderBy:{updatedAt:"desc"}},diagnoses:true,diagnosticOrders:{include:{results:true,specimens:true}},prescriptions:{include:{items:{include:{medication:true}}}}}});if(!encounter)throw new WonFlowApiError(404,"encounter-not-found","The encounter could not be found.");
  // Every note view is audited — this response is the only place a clinician reads a note's content.
  await database.auditEvent.create({data:{tenantId:c.tenantId,branchId:encounter.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"encounter.notes.viewed",entityType:"encounter",entityId:encounter.id,severity:"INFORMATION",sourceApplication:c.sourceApplication}});
  return encounter;}
async saveDraft(rc:WonFlowRequestContext,id:string,input:{noteId?:string;noteType:string;content:object;version?:number}){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"encounters.manage");const encounter=await this.requireEncounterAccess(c.tenantId,doctor.id,id);
  if(input.noteId){
    const existing=await database.encounterNote.findFirst({where:{id:input.noteId,tenantId:c.tenantId,encounterId:id}});
    if(!existing)throw new WonFlowApiError(404,"note-not-found","The clinical note could not be found.");
    // Signed (or previously amended) notes are immutable: editing one creates a new row that
    // references the original instead of overwriting it, and both stay readable.
    if(existing.status!=="DRAFT"){
      return database.$transaction(async tx=>{
        const amendment=await tx.encounterNote.create({data:{tenantId:c.tenantId,encounterId:id,authorMembershipId:c.membershipId!,noteType:input.noteType,content:{...input.content,amendsNoteId:existing.id}}});
        if(existing.status==="SIGNED")await tx.encounterNote.update({where:{id:existing.id},data:{status:"AMENDED"}});
        await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId:encounter.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"encounter.note.amended",entityType:"encounter-note",entityId:amendment.id,severity:"INFORMATION",sourceApplication:c.sourceApplication}});
        return amendment;
      });
    }
    if(existing.authorMembershipId!==c.membershipId)throw new WonFlowApiError(403,"not-author","Only the author may edit this draft.");
    if(encounter.status!=="PLANNED"&&encounter.status!=="IN_PROGRESS")throw new WonFlowApiError(404,"encounter-not-editable","The encounter is not available for editing.");
    const result=await database.encounterNote.updateMany({where:{id:input.noteId,tenantId:c.tenantId,encounterId:id,authorMembershipId:c.membershipId!,status:"DRAFT",version:input.version},data:{content:input.content,version:{increment:1}}});
    if(result.count!==1)throw new WonFlowApiError(409,"clinical-draft-conflict","This draft changed in another session. Reload before continuing.");
    return database.encounterNote.findUnique({where:{id:input.noteId}});
  }
  if(encounter.status!=="PLANNED"&&encounter.status!=="IN_PROGRESS")throw new WonFlowApiError(404,"encounter-not-editable","The encounter is not available for editing.");
  return database.encounterNote.create({data:{tenantId:c.tenantId,encounterId:id,authorMembershipId:c.membershipId!,noteType:input.noteType,content:input.content}});}
/** A configured clinician's note can only be signed by their assigned supervisor — never by the author, and never by editing the request to claim a different role. */
async signNote(rc:WonFlowRequestContext,encounterId:string,noteId:string){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"encounters.sign");return database.$transaction(async tx=>{
  const note=await tx.encounterNote.findFirst({where:{id:noteId,tenantId:c.tenantId,encounterId,status:"DRAFT"}});
  if(!note)throw new WonFlowApiError(409,"note-not-signable","The clinical note cannot be signed.");
  const isAuthor=note.authorMembershipId===c.membershipId;
  const authorDoctor=await tx.doctorProfile.findFirst({where:{tenantId:c.tenantId,staffProfile:{membershipId:note.authorMembershipId}}});
  if(authorDoctor?.requiresCountersignature){
    if(isAuthor)throw new WonFlowApiError(403,"countersignature-required","Your notes require countersignature by your supervisor and cannot be self-signed.");
    if(authorDoctor.supervisorDoctorId!==doctor.id)throw new WonFlowApiError(403,"not-assigned-supervisor","Only this clinician's assigned supervisor may countersign this note.");
  }else if(!isAuthor){
    throw new WonFlowApiError(403,"not-author","Only the author may sign this note.");
  }
  const signed=await tx.encounterNote.update({where:{id:note.id},data:{status:"SIGNED",signedAt:new Date(),releasedAt:new Date()}});
  // A countersignature reviews and releases the note; it does not reassign the encounter to the supervisor.
  if(isAuthor)await tx.encounter.update({where:{id:encounterId},data:{doctorId:doctor.id,status:"IN_PROGRESS",signedAt:new Date()}});
  await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId:c.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:isAuthor?"encounter.note.signed":"encounter.note.countersigned",entityType:"encounter-note",entityId:signed.id,severity:"INFORMATION",sourceApplication:c.sourceApplication}});
  return signed;
});}
async addDiagnosis(rc:WonFlowRequestContext,id:string,input:{codeSystem?:string;code?:string;display:string;certainty:"PROVISIONAL"|"DIFFERENTIAL"|"CONFIRMED"|"REFUTED";isPrimary?:boolean;notes?:string}){const{context:c}=await this.resolveDoctor(rc);requirePermission(c,"encounters.manage");const e=await database.encounter.findFirst({where:{id,tenantId:c.tenantId}});if(!e)throw new WonFlowApiError(404,"encounter-not-found","The encounter could not be found.");return database.encounterDiagnosis.create({data:{tenantId:c.tenantId,patientId:e.patientId,encounterId:id,recordedByMembershipId:c.membershipId!,codeSystem:input.codeSystem??null,code:input.code??null,display:input.display.trim(),certainty:input.certainty,isPrimary:input.isPrimary??false,notes:input.notes?.trim()||null}});}
async recordObservation(rc:WonFlowRequestContext,id:string,input:{code:string;display:string;valueNumber?:number;valueText?:string;unit?:string;observedAt:string}){const{context:c}=await this.resolveDoctor(rc);requirePermission(c,"encounters.manage");const e=await database.encounter.findFirst({where:{id,tenantId:c.tenantId}});if(!e)throw new WonFlowApiError(404,"encounter-not-found","The encounter could not be found.");return database.clinicalObservation.create({data:{tenantId:c.tenantId,patientId:e.patientId,encounterId:id,recordedByMembershipId:c.membershipId!,code:input.code,display:input.display,valueNumber:input.valueNumber,valueText:input.valueText??null,unit:input.unit??null,observedAt:new Date(input.observedAt)}});}
async createOrder(rc:WonFlowRequestContext,id:string,input:{type:"LABORATORY"|"RADIOLOGY";code:string;name:string;priority?:string;specimenOrBodySite?:string;clinicalReason?:string}){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,input.type==="LABORATORY"?"laboratory.orders.manage":"radiology.orders.manage");const e=await database.encounter.findFirst({where:{id,tenantId:c.tenantId,doctorId:doctor.id,branchId:requireBranchId(c)}});if(!e)throw new WonFlowApiError(404,"encounter-not-found","The encounter could not be found.");return database.diagnosticOrder.create({data:{tenantId:c.tenantId,branchId:e.branchId,patientId:e.patientId,encounterId:e.id,orderedByMembershipId:c.membershipId!,type:input.type,status:"ORDERED",priority:input.priority??"routine",code:input.code.trim(),name:input.name.trim(),specimenOrBodySite:input.specimenOrBodySite?.trim()||null,clinicalReason:input.clinicalReason?.trim()||null,orderedAt:new Date()}});}
async createPrescription(rc:WonFlowRequestContext,id:string,input:{instructions?:string;items:{medicationId:string;dose:string;route?:string;frequency:string;duration?:string;quantity?:number;instructions?:string}[]}){const{context:c,doctor}=await this.resolveDoctor(rc);requirePermission(c,"encounters.manage");const e=await database.encounter.findFirst({where:{id,tenantId:c.tenantId,doctorId:doctor.id}});if(!e)throw new WonFlowApiError(404,"encounter-not-found","The encounter could not be found.");return database.prescription.create({data:{tenantId:c.tenantId,patientId:e.patientId,encounterId:e.id,doctorId:doctor.id,status:"ACTIVE",prescribedAt:new Date(),instructions:input.instructions?.trim()||null,items:{create:input.items.map(x=>({medicationId:x.medicationId,dose:x.dose,route:x.route??null,frequency:x.frequency,duration:x.duration??null,quantity:x.quantity,instructions:x.instructions??null}))}},include:{items:true}});}}
export const doctorService=new DoctorService();
