import type { IsoDateTime, PracticePrivilege, WonFlowId } from "@wonflow/contracts";
import type { WonFlowOrganizationScope } from "./practice-service";
export interface PracticeClinicianActor { userId:WonFlowId;teamMemberId:WonFlowId }
export interface PracticePatientActor { patientAccountId:WonFlowId;patientId:WonFlowId }
export type ClinicianDocumentReviewStatus="unreviewed"|"reviewed"|"needs-clarification"|"not-relevant"|"superseded";
export type ClinicianDocumentVisibility="clinician-only"|"released-to-patient";
export type ClinicianDocumentScanStatus="pending"|"clean"|"quarantined"|"failed";
export interface ClinicianDocumentPatientSummary {patientId:WonFlowId;displayName:string;recordNumber:string;dateOfBirth?:string;ageLabel?:string;sexLabel?:string;allergies:string[];activeProblems:string[];recentEncounterSummaries:string[]}
export interface ClinicianDocumentInboxItem {documentId:WonFlowId;patientId:WonFlowId;patientDisplayName:string;patientRecordNumber:string;title:string;categoryLabel:string;clinicalDate:string;uploadedAt:IsoDateTime;sourceLabel:string;reviewStatus:ClinicianDocumentReviewStatus;visibility:ClinicianDocumentVisibility;scanStatus:ClinicianDocumentScanStatus;assignedReviewerTeamMemberId?:WonFlowId;pageCount?:number;sizeBytes:number;mimeType:string}
export interface ClinicianDocumentPage {pageNumber:number;width:number;height:number;previewToken:string}
export interface ClinicianDocumentViewerModel {document:ClinicianDocumentInboxItem;patient:ClinicianDocumentPatientSummary;pages:ClinicianDocumentPage[];privateClinicalNote?:string;reviewReason?:string;openedAt:IsoDateTime;accessEventId:WonFlowId}
export interface GetClinicianDocumentInboxInput {actor:PracticeClinicianActor;practiceLocationId?:WonFlowId;reviewStatus?:ClinicianDocumentReviewStatus;patientId?:WonFlowId}
export interface OpenClinicianDocumentInput {actor:PracticeClinicianActor;documentId:WonFlowId;reason:string}
export interface SaveClinicianDocumentReviewInput {actor:PracticeClinicianActor;documentId:WonFlowId;reviewStatus:Exclude<ClinicianDocumentReviewStatus,"unreviewed">;privateClinicalNote?:string;reviewReason?:string;visibility:ClinicianDocumentVisibility;idempotencyKey:string}
export interface CreatePracticeDocumentRequestInput {actor:PracticeClinicianActor;patientId:WonFlowId;title:string;instructions?:string;categoryCode?:string;dueAt?:IsoDateTime;practiceLocationId?:WonFlowId;idempotencyKey:string}
export type PracticeConsultationWorkflowStatus="draft"|"awaiting-countersignature"|"signed"|"released"|"amended"|"rejected";
export type PracticeConsultationReleaseSection="assessment"|"plan"|"medicines"|"patient-instructions"|"investigations"|"follow-up";
export interface PracticeConsultationMedicineDraft {medicineName:string;strength?:string;route?:string;dose:string;frequency:string;duration:string;instructions?:string}
export interface PracticeConsultationInvestigationDraft {code?:string;label:string;instructions?:string;urgency:"routine"|"urgent"}
export interface PracticeConsultationCompletionDraft {assessment:string;plan:string;medicines:PracticeConsultationMedicineDraft[];patientInstructions:string;requestedInvestigations:PracticeConsultationInvestigationDraft[];followUpDate?:string;followUpInstructions?:string;releasedSections:PracticeConsultationReleaseSection[]}
export interface PracticeConsultationSignatureProjection {id:WonFlowId;consultationId:WonFlowId;subjectType:"consultation"|"message-reply";subjectId:WonFlowId;authorTeamMemberId:WonFlowId;authorDisplayName:string;supervisorTeamMemberId?:WonFlowId;supervisorDisplayName?:string;status:"draft"|"pending"|"signed"|"rejected";authoredAt:IsoDateTime;signedAt?:IsoDateTime;rejectedAt?:IsoDateTime;rejectionReason?:string}
export interface PracticeConsultationAmendmentProjection {id:WonFlowId;consultationId:WonFlowId;originalSignatureId:WonFlowId;authorTeamMemberId:WonFlowId;authorDisplayName:string;reason:string;content:string;createdAt:IsoDateTime}
export interface PracticeConsultationCompletionView {consultationId:WonFlowId;patientId:WonFlowId;patientDisplayName:string;appointmentId?:WonFlowId;practiceLocationId?:WonFlowId;author:{teamMemberId:WonFlowId;displayName:string;supervisionLevel:"independent"|"countersigned"|"non-clinical";supervisorTeamMemberId?:WonFlowId};status:PracticeConsultationWorkflowStatus;draft:PracticeConsultationCompletionDraft;signature?:PracticeConsultationSignatureProjection;amendments:PracticeConsultationAmendmentProjection[];canEdit:boolean;canComplete:boolean;canCountersign:boolean;canAmend:boolean}
export interface SavePracticeConsultationCompletionInput {actor:PracticeClinicianActor;consultationId:WonFlowId;draft:PracticeConsultationCompletionDraft;idempotencyKey:string}
export interface CountersignPracticeConsultationInput {actor:PracticeClinicianActor;consultationId:WonFlowId;signatureId:WonFlowId;decision:"sign"|"reject";reason?:string;idempotencyKey:string}
export interface CreatePracticeConsultationAmendmentInput {actor:PracticeClinicianActor;consultationId:WonFlowId;reason:string;content:string;idempotencyKey:string}
export interface PracticeCountersignatureQueueItem {consultation:PracticeConsultationCompletionView;submittedAt:IsoDateTime;ageMinutes:number}
export type PracticeMessageThreadStatus="open"|"awaiting-practice"|"awaiting-patient"|"resolved"|"closed";export type PracticeMessagePriority="routine"|"high"|"urgent";
export interface PracticeMessageCategoryOption {code:string;label:string;description?:string;responseCommitmentMinutes:number;active:boolean}
export interface PracticeMessageSafetyProjection {contentBlockId:WonFlowId;version:number;title:string;body:string;effectiveFrom:IsoDateTime;alreadyAcknowledged:boolean}
export interface PracticeMessageProjection {id:WonFlowId;threadId:WonFlowId;authorType:"patient"|"team-member";authorDisplayName:string;body:string;attachedDocumentIds:WonFlowId[];sentAt?:IsoDateTime;deliveryStatus:"draft"|"pending-countersignature"|"sent"|"rejected";signature?:PracticeConsultationSignatureProjection}
export interface PracticeMessageThreadProjection {id:WonFlowId;patientId:WonFlowId;patientDisplayName:string;patientRecordNumber:string;subject:string;categoryCode:string;categoryLabel:string;priority:PracticeMessagePriority;status:PracticeMessageThreadStatus;assignedTeamMemberId?:WonFlowId;assignedTeamMemberName?:string;createdAt:IsoDateTime;lastMessageAt:IsoDateTime;responseDueAt?:IsoDateTime;overdue:boolean;escalationLevel:number;messages:PracticeMessageProjection[]}
export interface PatientMessageWorkspace {actor:PracticePatientActor;safetyNotice:PracticeMessageSafetyProjection;responseCommitmentLabel:string;categories:PracticeMessageCategoryOption[];attachableDocuments:{id:WonFlowId;title:string;categoryLabel:string;clinicalDate:string}[];threads:PracticeMessageThreadProjection[]}
export interface PracticeMessageTriageWorkspace {actor:PracticeClinicianActor;categories:PracticeMessageCategoryOption[];threads:PracticeMessageThreadProjection[];assignableMembers:{id:WonFlowId;displayName:string;privileges:PracticePrivilege[]}[]}
export interface AcknowledgePracticeMessageSafetyInput {actor:PracticePatientActor;contentBlockId:WonFlowId;version:number;acknowledgedAt:IsoDateTime}
export interface CreatePatientMessageThreadInput {actor:PracticePatientActor;subject:string;categoryCode:string;body:string;attachedDocumentIds:WonFlowId[];idempotencyKey:string}
export interface SendPatientMessageInput {actor:PracticePatientActor;threadId:WonFlowId;body:string;attachedDocumentIds:WonFlowId[];idempotencyKey:string}
export interface SavePracticeMessageTriageInput {actor:PracticeClinicianActor;threadId:WonFlowId;assignedTeamMemberId?:WonFlowId;priority:PracticeMessagePriority;status:PracticeMessageThreadStatus;reason:string;idempotencyKey:string}
export interface SendPracticeMessageReplyInput {actor:PracticeClinicianActor;threadId:WonFlowId;body:string;attachedDocumentIds:WonFlowId[];idempotencyKey:string}
export interface CountersignPracticeMessageReplyInput {actor:PracticeClinicianActor;threadId:WonFlowId;messageId:WonFlowId;signatureId:WonFlowId;decision:"sign"|"reject";reason?:string;idempotencyKey:string}
export interface WonFlowPracticeClinicalWorkflowService {getClinicianDocumentInbox(scope:WonFlowOrganizationScope,input:GetClinicianDocumentInboxInput,signal?:AbortSignal):Promise<ClinicianDocumentInboxItem[]>;openClinicianDocument(scope:WonFlowOrganizationScope,input:OpenClinicianDocumentInput,signal?:AbortSignal):Promise<ClinicianDocumentViewerModel>;saveClinicianDocumentReview(scope:WonFlowOrganizationScope,input:SaveClinicianDocumentReviewInput,signal?:AbortSignal):Promise<ClinicianDocumentViewerModel>;createPracticeDocumentRequest(scope:WonFlowOrganizationScope,input:CreatePracticeDocumentRequestInput,signal?:AbortSignal):Promise<{requestId:WonFlowId;createdAt:IsoDateTime}>;getPracticeConsultationCompletionView(scope:WonFlowOrganizationScope,consultationId:WonFlowId,actor:PracticeClinicianActor,signal?:AbortSignal):Promise<PracticeConsultationCompletionView>;savePracticeConsultationCompletion(scope:WonFlowOrganizationScope,input:SavePracticeConsultationCompletionInput,signal?:AbortSignal):Promise<PracticeConsultationCompletionView>;getPracticeCountersignatureQueue(scope:WonFlowOrganizationScope,actor:PracticeClinicianActor,signal?:AbortSignal):Promise<PracticeCountersignatureQueueItem[]>;countersignPracticeConsultation(scope:WonFlowOrganizationScope,input:CountersignPracticeConsultationInput,signal?:AbortSignal):Promise<PracticeConsultationCompletionView>;createPracticeConsultationAmendment(scope:WonFlowOrganizationScope,input:CreatePracticeConsultationAmendmentInput,signal?:AbortSignal):Promise<PracticeConsultationCompletionView>;getPatientMessageWorkspace(scope:WonFlowOrganizationScope,actor:PracticePatientActor,signal?:AbortSignal):Promise<PatientMessageWorkspace>;acknowledgePracticeMessageSafety(scope:WonFlowOrganizationScope,input:AcknowledgePracticeMessageSafetyInput,signal?:AbortSignal):Promise<void>;createPatientMessageThread(scope:WonFlowOrganizationScope,input:CreatePatientMessageThreadInput,signal?:AbortSignal):Promise<PracticeMessageThreadProjection>;sendPatientMessage(scope:WonFlowOrganizationScope,input:SendPatientMessageInput,signal?:AbortSignal):Promise<PracticeMessageThreadProjection>;getPracticeMessageTriageWorkspace(scope:WonFlowOrganizationScope,actor:PracticeClinicianActor,practiceLocationId?:WonFlowId,signal?:AbortSignal):Promise<PracticeMessageTriageWorkspace>;savePracticeMessageTriage(scope:WonFlowOrganizationScope,input:SavePracticeMessageTriageInput,signal?:AbortSignal):Promise<PracticeMessageThreadProjection>;sendPracticeMessageReply(scope:WonFlowOrganizationScope,input:SendPracticeMessageReplyInput,signal?:AbortSignal):Promise<PracticeMessageThreadProjection>;countersignPracticeMessageReply(scope:WonFlowOrganizationScope,input:CountersignPracticeMessageReplyInput,signal?:AbortSignal):Promise<PracticeMessageThreadProjection>}
