"use client";
import * as React from "react";
import { cn } from "../lib/utils";
import { Button } from "./button";

const control="h-[34px] w-full rounded-[var(--radius-control)] border border-[var(--line-2)] bg-[var(--surface)] px-3 text-sm text-[var(--ink-900)] disabled:text-[var(--ink-400)]";
export function IconButton({label,className,...props}:React.ComponentProps<"button">&{label:string}){return <button aria-label={label} className={cn("inline-flex size-[34px] items-center justify-center rounded-[var(--radius-control)] border border-[var(--line)] bg-[var(--surface)] text-[var(--ink-700)] hover:bg-[var(--muted)]",className)} {...props}/>}
export function Textarea({className,...props}:React.ComponentProps<"textarea">){return <textarea className={cn(control,"min-h-24 py-2",className)} {...props}/>}
export function Select({className,...props}:React.ComponentProps<"select">){return <select className={cn(control,className)} {...props}/>}
export function Combobox({options,value,onChange,label}:Readonly<{options:readonly {value:string;label:string}[];value:string;onChange:(value:string)=>void;label:string}>){return <label className="block"><span className="sr-only">{label}</span><input className={control} list={`${label}-options`} value={value} onChange={event=>onChange(event.target.value)}/><datalist id={`${label}-options`}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</datalist></label>}
export function Checkbox({label,className,...props}:React.ComponentProps<"input">&{label:string}){return <label className="inline-flex items-center gap-2 text-sm"><input type="checkbox" className={cn("size-4 accent-[var(--blue-600)]",className)} {...props}/><span>{label}</span></label>}
export function Radio({label,className,...props}:React.ComponentProps<"input">&{label:string}){return <label className="inline-flex items-center gap-2 text-sm"><input type="radio" className={cn("size-4 accent-[var(--blue-600)]",className)} {...props}/><span>{label}</span></label>}
export function Switch({label,checked,onCheckedChange,disabled=false}:Readonly<{label:string;checked:boolean;onCheckedChange:(checked:boolean)=>void;disabled?:boolean}>){return <button type="button" role="switch" aria-checked={checked} disabled={disabled} onClick={()=>onCheckedChange(!checked)} className="inline-flex items-center gap-2 text-sm"><span className={cn("flex h-5 w-9 items-center rounded-full border p-0.5",checked?"border-[var(--blue-600)] bg-[var(--blue-600)]":"border-[var(--line-2)] bg-[var(--muted)]")}><span className={cn("size-3.5 rounded-full bg-[var(--surface)]",checked&&"ml-auto")}/></span>{label}</button>}
export function DatePicker(props:React.ComponentProps<"input">){return <input type="date" className={control} {...props}/>}
export function TimePicker(props:React.ComponentProps<"input">){return <input type="time" className={control} {...props}/>}
export function MoneyInput({currency,valueMinor,onValueMinorChange,...props}:Omit<React.ComponentProps<"input">,"value"|"onChange">&{currency:string;valueMinor:number;onValueMinorChange:(value:number)=>void}){const [display,setDisplay]=React.useState((valueMinor/100).toFixed(2));React.useEffect(()=>setDisplay((valueMinor/100).toFixed(2)),[valueMinor]);return <label className="flex"><span className="flex h-[34px] items-center rounded-l-[var(--radius-control)] border border-r-0 border-[var(--line-2)] bg-[var(--muted)] px-2 text-xs">{currency}</span><input inputMode="decimal" className={cn(control,"rounded-l-none")} value={display} onChange={e=>setDisplay(e.target.value)} onBlur={()=>{const [whole="0",fraction=""]=display.replace(/[^0-9.]/g,"").split(".");const minor=Number(whole||0)*100+Number((fraction+"00").slice(0,2));onValueMinorChange(Number.isSafeInteger(minor)?minor:0);setDisplay((Number.isSafeInteger(minor)?minor:0)/100+"");}} {...props}/></label>}
export function FileDrop({label="Choose files",onFiles}:Readonly<{label?:string;onFiles:(files:FileList)=>void}>){return <label className="flex min-h-24 cursor-pointer items-center justify-center rounded-[var(--radius-card)] border border-dashed border-[var(--line-2)] bg-[var(--muted)] p-4 text-sm text-[var(--ink-500)]">{label}<input className="sr-only" type="file" multiple onChange={e=>e.target.files&&onFiles(e.target.files)}/></label>}
export function SegmentedControl({label,options,value,onChange}:Readonly<{label:string;options:readonly {value:string;label:string}[];value:string;onChange:(value:string)=>void}>){return <fieldset><legend className="sr-only">{label}</legend><div className="inline-flex rounded-[var(--radius-control)] border border-[var(--line-2)] p-1">{options.map(option=><Button key={option.value} size="sm" variant={option.value===value?"primary":"ghost"} onClick={()=>onChange(option.value)}>{option.label}</Button>)}</div></fieldset>}
