import * as React from "react";
import { cn } from "../lib/utils";
import { Button } from "./button";
import { Skeleton } from "./skeleton";

export function Table({loading=false,empty,children,className,...props}:React.ComponentProps<"table">&{loading?:boolean;empty?:React.ReactNode}){if(loading)return <div className="space-y-2" aria-label="Loading table">{Array.from({length:5},(_,i)=><Skeleton key={i} className="h-10 w-full"/>)}</div>;if(empty)return <>{empty}</>;return <div className="overflow-x-auto rounded-[var(--radius-card)] border border-[var(--line)]"><table className={cn("w-full border-collapse text-left text-[13px]",className)} {...props}>{children}</table></div>}
export function TableHead({className,...props}:React.ComponentProps<"thead">){return <thead className={cn("sticky top-0 z-10 bg-[var(--muted)] text-[11px] font-medium uppercase tracking-[.06em] text-[var(--ink-500)] [&_th]:h-10 [&_th]:px-3",className)} {...props}/>}
export function TableBody({className,...props}:React.ComponentProps<"tbody">){return <tbody className={cn("divide-y divide-[var(--line)] [&_td]:h-10 [&_td]:px-3",className)} {...props}/>}
export function TableToolbar({className,...props}:React.ComponentProps<"div">){return <div className={cn("mb-3 flex flex-wrap items-center justify-between gap-3",className)} {...props}/>}
export function Pagination({page,pageCount,onChange}:Readonly<{page:number;pageCount:number;onChange:(page:number)=>void}>){return <nav aria-label="Pagination" className="flex items-center justify-end gap-2"><Button variant="secondary" size="sm" disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</Button><span className="text-xs text-[var(--ink-500)]">Page {page} of {pageCount}</span><Button variant="secondary" size="sm" disabled={page>=pageCount} onClick={()=>onChange(page+1)}>Next</Button></nav>}
export function DescriptionList({items,className}:Readonly<{items:readonly {term:string;description:React.ReactNode}[];className?:string}>){return <dl className={cn("grid gap-3 sm:grid-cols-2",className)}>{items.map(item=><div key={item.term}><dt className="text-[11px] font-medium uppercase tracking-[.06em] text-[var(--ink-500)]">{item.term}</dt><dd className="mt-1 text-[13px] text-[var(--ink-900)]">{item.description}</dd></div>)}</dl>}
export function Stat({label,value,detail}:Readonly<{label:string;value:React.ReactNode;detail?:string}>){return <div><p className="text-[11px] font-medium uppercase tracking-[.06em] text-[var(--ink-500)]">{label}</p><p className="mt-1 text-[26px] font-semibold leading-tight text-[var(--ink-900)]">{value}</p>{detail&&<p className="mt-1 text-xs text-[var(--ink-500)]">{detail}</p>}</div>}
export function Timeline({items}:Readonly<{items:readonly {id:string;title:string;description?:string;time?:string}[]}>){return <ol className="space-y-4 border-l border-[var(--line-2)] pl-4">{items.map(item=><li key={item.id} className="relative before:absolute before:-left-[21px] before:top-1 before:size-2 before:rounded-full before:bg-[var(--blue-600)]"><p className="text-[13px] font-medium text-[var(--ink-900)]">{item.title}</p>{item.description&&<p className="text-xs text-[var(--ink-500)]">{item.description}</p>}{item.time&&<time className="text-[11px] text-[var(--ink-400)]">{item.time}</time>}</li>)}</ol>}
export function EmptyState({title,description,action}:Readonly<{title:string;description:string;action?:React.ReactNode}>){return <div className="rounded-[var(--radius-card)] border border-dashed border-[var(--line-2)] p-6 text-center"><h3 className="text-base font-semibold">{title}</h3><p className="mx-auto mt-1 max-w-lg text-sm text-[var(--ink-500)]">{description}</p>{action&&<div className="mt-4">{action}</div>}</div>}
