import * as React from "react";
import { cn } from "../lib/utils";

const tones={info:"border-[var(--blue-600)]",success:"border-[var(--green-600)]",warning:"border-[var(--amber-600)]",danger:"border-[var(--red-600)]"} as const;
export function StatusDot({status,label}:Readonly<{status:keyof typeof tones;label:string}>){return <span className="inline-flex items-center gap-2 text-xs"><span className={cn("size-2 rounded-full",status==="info"&&"bg-[var(--blue-600)]",status==="success"&&"bg-[var(--green-600)]",status==="warning"&&"bg-[var(--amber-600)]",status==="danger"&&"bg-[var(--red-600)]")}/>{label}</span>}
export function Alert({title,children,tone="info",className}:React.PropsWithChildren<{title:string;tone?:keyof typeof tones;className?:string}>){return <div role={tone==="danger"?"alert":"status"} className={cn("rounded-[var(--radius-card)] border-l-2 border-y border-r border-y-[var(--line)] border-r-[var(--line)] bg-[var(--surface)] p-4",tones[tone],className)}><h3 className="text-sm font-medium">{title}</h3><div className="mt-1 text-xs text-[var(--ink-500)]">{children}</div></div>}
export function Toast({title,description,tone="info",onDismiss}:Readonly<{title:string;description?:string;tone?:keyof typeof tones;onDismiss?:()=>void}>){return <div role="status" aria-live="polite" className={cn("w-80 rounded-[var(--radius-card)] border bg-[var(--surface)] p-4 shadow-[var(--shadow-md)]",tones[tone])}><div className="flex justify-between gap-3"><div><p className="text-sm font-medium">{title}</p>{description&&<p className="mt-1 text-xs text-[var(--ink-500)]">{description}</p>}</div>{onDismiss&&<button aria-label="Dismiss notification" onClick={onDismiss}>×</button>}</div></div>}
export function Spinner({label="Loading"}:Readonly<{label?:string}>){return <span role="status" className="inline-flex items-center gap-2 text-xs text-[var(--ink-500)]"><span className="size-4 animate-spin rounded-full border-2 border-[var(--line-2)] border-t-[var(--blue-600)]"/><span>{label}</span></span>}
export function ProgressBar({value,label}:Readonly<{value:number;label:string}>){const safe=Math.max(0,Math.min(100,value));return <div><div className="mb-1 flex justify-between text-xs"><span>{label}</span><span>{safe}%</span></div><div className="h-2 overflow-hidden rounded-[var(--radius-control)] bg-[var(--muted)]"><div className="h-full bg-[var(--blue-600)]" style={{width:`${safe}%`}}/></div></div>}
export function ErrorState({title="Unable to load this page",description,onRetry}:Readonly<{title?:string;description:string;onRetry?:()=>void}>){return <Alert title={title} tone="danger"><p>{description}</p>{onRetry&&<button className="mt-3 font-medium text-[var(--blue-600)]" onClick={onRetry}>Try again</button>}</Alert>}
export function NotAuthorized({requirement,contact}:Readonly<{requirement:string;contact:string}>){return <Alert title="You do not have access" tone="warning">This page requires {requirement}. Ask {contact} for access.</Alert>}
export function NotConfigured({description,action}:Readonly<{description:string;action:React.ReactNode}>){return <Alert title="Setup required" tone="info"><p>{description}</p><div className="mt-3">{action}</div></Alert>}
