"use client";
import * as React from "react";
import { cn } from "../lib/utils";
import { Modal } from "./overlay";
import { Input } from "./input";

export function Tabs({items,value,onChange}:Readonly<{items:readonly {value:string;label:string}[];value:string;onChange:(value:string)=>void}>){return <div role="tablist" className="flex border-b border-[var(--line)]">{items.map(item=><button key={item.value} role="tab" aria-selected={item.value===value} className={cn("h-[34px] border-b-2 px-3 text-sm",item.value===value?"border-[var(--blue-600)] text-[var(--blue-600)]":"border-transparent text-[var(--ink-500)]")} onClick={()=>onChange(item.value)}>{item.label}</button>)}</div>}
export function Breadcrumb({items}:Readonly<{items:readonly {label:string;href?:string}[]}>){return <nav aria-label="Breadcrumb"><ol className="flex flex-wrap items-center gap-2 text-xs text-[var(--ink-500)]">{items.map((item,index)=><li key={`${item.label}-${index}`} className="flex gap-2">{index>0&&<span aria-hidden>/</span>}{item.href?<a className="hover:text-[var(--blue-600)]" href={item.href}>{item.label}</a>:<span aria-current="page">{item.label}</span>}</li>)}</ol></nav>}
export function SidebarNav({groups}:Readonly<{groups:readonly {label:string;items:readonly {label:string;href:string;active?:boolean;icon?:React.ReactNode}[]}[]}>){return <nav>{groups.map(group=><section key={group.label} className="mb-6"><h2 className="mb-2 px-3 text-[11px] font-medium uppercase tracking-[.06em] text-[var(--ink-500)]">{group.label}</h2><ul className="space-y-1">{group.items.map(item=><li key={item.href}><a href={item.href} aria-current={item.active?"page":undefined} className={cn("flex h-[34px] items-center gap-3 border-l-2 px-3 text-sm hover:bg-[var(--muted)]",item.active?"border-[var(--blue-600)] bg-[var(--blue-50)] font-medium text-[var(--ink-900)]":"border-transparent text-[var(--ink-700)]")}>{item.icon}{item.label}</a></li>)}</ul></section>)}</nav>}
export function CommandPalette({open,onClose,items,onSelect}:Readonly<{open:boolean;onClose:()=>void;items:readonly {id:string;label:string;detail?:string}[];onSelect:(id:string)=>void}>){const[query,setQuery]=React.useState("");const[index,setIndex]=React.useState(0);const filtered=items.filter(item=>`${item.label} ${item.detail??""}`.toLowerCase().includes(query.toLowerCase()));React.useEffect(()=>setIndex(0),[query]);return <Modal open={open} onClose={onClose} title="Search"><Input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setIndex(Math.min(index+1,filtered.length-1))}if(e.key==="ArrowUp"){e.preventDefault();setIndex(Math.max(index-1,0))}if(e.key==="Enter"&&filtered[index])onSelect(filtered[index].id)}} placeholder="Search navigation, patients and actions"/><ul className="mt-3 max-h-80 overflow-y-auto">{filtered.map((item,i)=><li key={item.id}><button className={cn("w-full rounded-[var(--radius-control)] px-3 py-2 text-left",i===index&&"bg-[var(--blue-50)]")} onMouseEnter={()=>setIndex(i)} onClick={()=>onSelect(item.id)}><span className="block text-sm font-medium">{item.label}</span>{item.detail&&<span className="text-xs text-[var(--ink-500)]">{item.detail}</span>}</button></li>)}</ul></Modal>}
