"use client";
import * as React from "react";
import { createPortal } from "react-dom";
import { cn } from "../lib/utils";
import { Button } from "./button";

function useOverlay(open:boolean,onClose:()=>void){const ref=React.useRef<HTMLDivElement>(null);React.useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null;const node=ref.current;node?.querySelector<HTMLElement>("button,[href],input,select,textarea,[tabindex]:not([tabindex='-1'])")?.focus();function keydown(event:KeyboardEvent){if(event.key==="Escape")onClose();if(event.key!=="Tab"||!node)return;const items=[...node.querySelectorAll<HTMLElement>("button,[href],input,select,textarea,[tabindex]:not([tabindex='-1'])")].filter(item=>!item.hasAttribute("disabled"));if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}document.addEventListener("keydown",keydown);return()=>{document.removeEventListener("keydown",keydown);previous?.focus()}},[open,onClose]);return ref}
function Overlay({open,onClose,title,children,drawer=false}:React.PropsWithChildren<{open:boolean;onClose:()=>void;title:string;drawer?:boolean}>){const ref=useOverlay(open,onClose);if(!open||typeof document==="undefined")return null;return createPortal(<div className="fixed inset-0 z-50 flex bg-[rgba(11,18,32,.36)]" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby="overlay-title" className={cn("bg-[var(--surface)] p-6 shadow-[var(--shadow-md)]",drawer?"ml-auto h-full w-full max-w-md":"m-auto w-[min(560px,calc(100%-32px))] rounded-[var(--radius-modal)]")}><div className="mb-4 flex items-center justify-between"><h2 id="overlay-title" className="text-base font-semibold">{title}</h2><button aria-label="Close" onClick={onClose}>×</button></div>{children}</div></div>,document.body)}
export function Modal(props:React.ComponentProps<typeof Overlay>){return <Overlay {...props}/>}
export function Drawer(props:Omit<React.ComponentProps<typeof Overlay>,"drawer">){return <Overlay drawer {...props}/>}
export function ConfirmDialog({open,title,description,confirmLabel="Confirm",danger=false,onConfirm,onClose}:Readonly<{open:boolean;title:string;description:string;confirmLabel?:string;danger?:boolean;onConfirm:()=>void;onClose:()=>void}>){return <Modal open={open} onClose={onClose} title={title}><p className="text-sm text-[var(--ink-500)]">{description}</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant={danger?"danger":"primary"} onClick={onConfirm}>{confirmLabel}</Button></div></Modal>}
export function Popover({trigger,children}:React.PropsWithChildren<{trigger:React.ReactNode}>){const[open,setOpen]=React.useState(false);return <span className="relative inline-block"><span onClick={()=>setOpen(!open)}>{trigger}</span>{open&&<span role="dialog" className="absolute right-0 top-full z-20 mt-2 block min-w-48 rounded-[var(--radius-card)] border border-[var(--line)] bg-[var(--surface)] p-3 shadow-[var(--shadow-md)]">{children}</span>}</span>}
export function Tooltip({label,children}:React.PropsWithChildren<{label:string}>){return <span className="group relative inline-flex">{children}<span role="tooltip" className="pointer-events-none absolute bottom-full left-0 z-20 mb-2 hidden whitespace-nowrap rounded-[var(--radius-control)] bg-[var(--ink-900)] px-2 py-1 text-xs text-white group-hover:block group-focus-within:block">{label}</span></span>}
