"use client";
import Link from "next/link";
import { useActionState } from "react";
import { bookPatientAppointmentAction } from "@/lib/patient/book-patient-appointment.action";
import { PatientAppointmentMutationFeedback } from "./patient-appointment-mutation-feedback";
import { PatientAppointmentSubmitButton } from "./patient-appointment-submit-button";
import { initialPatientAppointmentMutationState } from "./patient-appointment-mutation-model";
import type { PatientAppointmentBookingView } from "./patient-appointment-booking-model";
export function PatientAppointmentBookingScreen({ model, submissionId }: { model: PatientAppointmentBookingView; submissionId: string }) { const [state, action] = useActionState(bookPatientAppointmentAction, initialPatientAppointmentMutationState); return <main id="main-content" className="mx-auto w-full max-w-4xl overflow-x-clip px-4 py-6 sm:px-6 sm:py-8"><Link href={model.appointmentsHref} className="inline-flex min-h-11 items-center text-sm font-semibold text-blue-700">← Back to appointments</Link><h1 className="mt-5 break-words text-3xl font-bold">Book appointment</h1>{!model.availability.available ? <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm">{model.availability.unavailableReasons.length ? model.availability.unavailableReasons.map((reason) => <p key={reason} className="break-words">{reason}</p>) : "Booking is unavailable."}</div> : <form action={action} className="mt-6 space-y-5"><input type="hidden" name="submissionId" value={submissionId} /><p className="text-sm">Select an appointment type and available time.</p><label className="block text-sm font-semibold">Offering<input className="mt-2 min-h-11 w-full rounded-xl border p-3" name="offeringId" required /></label><label className="block text-sm font-semibold">Time<input className="mt-2 min-h-11 w-full rounded-xl border p-3" name="slotId" required /></label><PatientAppointmentMutationFeedback state={state} /><PatientAppointmentSubmitButton label="Book appointment" pendingLabel="Booking appointment…" /></form>}</main>; }
