"use client";
import Link from "next/link";
import { useActionState } from "react";
import { cancelPatientAppointmentAction } from "@/lib/patient/cancel-patient-appointment.action";
import { PatientAppointmentCard } from "./patient-appointment-card";
import { PatientAppointmentMutationFeedback } from "./patient-appointment-mutation-feedback";
import { PatientAppointmentSubmitButton } from "./patient-appointment-submit-button";
import { initialPatientAppointmentMutationState } from "./patient-appointment-mutation-model";
import type { PatientAppointmentDetailsView } from "./patient-appointment-details-model";
export function PatientAppointmentCancellationScreen({ details, submissionId }: { details: PatientAppointmentDetailsView; submissionId: string }) { const [state, action] = useActionState(cancelPatientAppointmentAction, initialPatientAppointmentMutationState); const href = `/patient/appointments/${encodeURIComponent(details.appointment.id)}`; return <main className="mx-auto max-w-3xl px-4 py-6"><Link href={href} className="inline-flex min-h-11 items-center text-sm font-semibold text-blue-700">← Back to appointment</Link><h1 className="mt-5 text-3xl font-bold">Cancel appointment</h1><div className="mt-6"><PatientAppointmentCard appointment={{ ...details.appointment, detailsHref: undefined }} /></div>{details.cancellation.available ? <form action={action} className="mt-5 rounded-2xl border border-red-200 bg-white p-5"><input type="hidden" name="appointmentId" value={details.appointment.id} /><input type="hidden" name="submissionId" value={submissionId} />{details.cancellation.consequence ? <p className="rounded-xl bg-amber-50 p-4 text-sm">{details.cancellation.consequence}</p> : null}{details.cancellation.acknowledgementRequired ? <label className="mt-4 flex gap-3 text-sm"><input required type="checkbox" name="acknowledgement" value="accepted" />I understand the cancellation consequence.</label> : null}<div className="mt-5"><PatientAppointmentMutationFeedback state={state} /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href={href} className="inline-flex min-h-11 items-center justify-center rounded-xl border px-4 py-2.5 text-sm font-semibold">Keep appointment</Link><PatientAppointmentSubmitButton destructive label="Cancel appointment" pendingLabel="Cancelling…" /></div></form> : <Link href={href} className="mt-5 inline-flex min-h-11 items-center rounded-xl border px-4 py-2.5 text-sm font-semibold">Return to appointment</Link>}</main>; }
