export const MAX_TENANT_CONTENT_LENGTH=50_000;
export const MAX_TEMPLATE_SUBJECT_LENGTH=240;
export const TENANT_TEMPLATE_VARIABLE_PATTERN=/\{\{\s*([a-zA-Z][a-zA-Z0-9_.-]*)\s*\}\}/g;
export interface TenantTemplateVariableDefinition{name:string;required:boolean;description?:string}
export function normalizeTenantVariableName(value:string){return value.trim().toLowerCase()}
export function extractTenantTemplateVariables(content:string){const variables=new Set<string>();for(const match of content.matchAll(TENANT_TEMPLATE_VARIABLE_PATTERN)){if(match[1])variables.add(normalizeTenantVariableName(match[1]))}return [...variables].sort()}
export function validateTenantTemplateVariables(content:string,definitions:readonly TenantTemplateVariableDefinition[]){const referencedVariables=extractTenantTemplateVariables(content);const counts=new Map<string,number>();for(const item of definitions){const name=normalizeTenantVariableName(item.name);counts.set(name,(counts.get(name)??0)+1)}const missingDefinitions=referencedVariables.filter((name)=>!counts.has(name));const missingRequiredReferences=definitions.filter((item)=>item.required).map((item)=>normalizeTenantVariableName(item.name)).filter((name)=>!referencedVariables.includes(name));const duplicateDefinitions=[...counts].filter(([,count])=>count>1).map(([name])=>name);return{valid:!missingDefinitions.length&&!missingRequiredReferences.length&&!duplicateDefinitions.length,referencedVariables,missingDefinitions,missingRequiredReferences,duplicateDefinitions}}
export function validateTenantAuthoredContent(value:string){const normalized=value.trim();if(!normalized)return "Content is required.";if(normalized.length>MAX_TENANT_CONTENT_LENGTH)return `Content must be no longer than ${MAX_TENANT_CONTENT_LENGTH.toLocaleString()} characters.`;return undefined}
export function validateEffectivePeriod(from:string,to:string){if(!from)return "An effective-from date is required.";if(to&&to<from)return "The effective-to date must not be earlier than the effective-from date.";return undefined}
