import{randomBytes}from"node:crypto";import{database}from"@wonflow/database";import{requireBranchId,requirePermission,requireTenantContext}from"@wonflow/contracts";import type{WonFlowRequestContext}from"@wonflow/contracts";import{WonFlowApiError}from"@/server/http/route-handler";
const accessionNumber=()=>`DX-${Date.now()}-${randomBytes(2).toString("hex").toUpperCase()}`;
/** Template codes that prove a released result reached each audience. */
export const PATIENT_RESULT_TEMPLATE="diagnostic-result-released";
export const CLINICIAN_RESULT_TEMPLATE="diagnostic-result-ready-for-review";
const orderInclude={patient:true,encounter:true,specimens:true,results:true};
export class DiagnosticsService{
/** Delivery receipts for released results, keyed by result id. */
private async getDeliveries(tenantId:string,resultIds:readonly string[]){const deliveries=new Map<string,{patient:boolean;clinician:boolean}>();if(resultIds.length===0)return deliveries;for(const id of resultIds)deliveries.set(id,{patient:false,clinician:false});const notifications=await database.notification.findMany({where:{tenantId,templateCode:{in:[PATIENT_RESULT_TEMPLATE,CLINICIAN_RESULT_TEMPLATE]}},select:{templateCode:true,payload:true}});for(const notification of notifications){const payload=notification.payload as{resultId?:string}|null;const resultId=payload?.resultId;if(!resultId)continue;const entry=deliveries.get(resultId);if(!entry)continue;if(notification.templateCode===PATIENT_RESULT_TEMPLATE)entry.patient=true;else entry.clinician=true;}return deliveries;}
private decorate<TResult extends{id:string},TOrder extends{results:TResult[]}>(orders:readonly TOrder[],deliveries:Map<string,{patient:boolean;clinician:boolean}>){return orders.map(order=>({...order,results:order.results.map(result=>({...result,delivery:deliveries.get(result.id)??{patient:false,clinician:false}}))}));}
async getWorklist(rc:WonFlowRequestContext,input:{type:"LABORATORY"|"RADIOLOGY";date:string}){const c=requireTenantContext(rc),branchId=requireBranchId(c);requirePermission(c,input.type==="LABORATORY"?"laboratory.orders.read":"radiology.orders.read");const orders=await database.diagnosticOrder.findMany({where:{tenantId:c.tenantId,branchId,type:input.type,createdAt:{gte:new Date(`${input.date}T00:00:00.000Z`),lte:new Date(`${input.date}T23:59:59.999Z`)}},include:orderInclude,orderBy:[{priority:"desc"},{createdAt:"asc"}]});return this.decorate(orders,await this.getDeliveries(c.tenantId,orders.flatMap(order=>order.results.map(result=>result.id))));}
async getOrder(rc:WonFlowRequestContext,orderId:string){const c=requireTenantContext(rc),order=await database.diagnosticOrder.findFirst({where:{id:orderId,tenantId:c.tenantId,branchId:requireBranchId(c)},include:orderInclude});if(!order)throw new WonFlowApiError(404,"diagnostic-order-not-found","The diagnostic order could not be found.");requirePermission(c,order.type==="LABORATORY"?"laboratory.orders.read":"radiology.orders.read");return this.decorate([order],await this.getDeliveries(c.tenantId,order.results.map(result=>result.id)))[0];}
async createSpecimen(rc:WonFlowRequestContext,orderId:string,input:{specimenType:string}){const c=requireTenantContext(rc);requirePermission(c,"laboratory.orders.manage");const order=await database.diagnosticOrder.findFirst({where:{id:orderId,tenantId:c.tenantId,branchId:requireBranchId(c),type:"LABORATORY"}});if(!order)throw new WonFlowApiError(404,"laboratory-order-not-found","The laboratory order could not be found.");if(!input.specimenType?.trim())throw new WonFlowApiError(400,"specimen-type-required","Enter the specimen type.");const accession=order.accessionNumber??accessionNumber();return database.$transaction(async tx=>{await tx.diagnosticOrder.update({where:{id:order.id},data:{accessionNumber:accession,status:"ACCEPTED"}});const specimen=await tx.diagnosticSpecimen.create({data:{tenantId:c.tenantId,diagnosticOrderId:order.id,accessionNumber:accession,specimenType:input.specimenType.trim()}});await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId:order.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"laboratory.specimen.collected",entityType:"diagnostic-specimen",entityId:specimen.id,severity:"INFORMATION",sourceApplication:c.sourceApplication}});return specimen;});}
/** Move an accepted order onto the bench so the worklist reflects live progress. */
async startProcessing(rc:WonFlowRequestContext,orderId:string){const c=requireTenantContext(rc),order=await database.diagnosticOrder.findFirst({where:{id:orderId,tenantId:c.tenantId,branchId:requireBranchId(c)}});if(!order)throw new WonFlowApiError(404,"diagnostic-order-not-found","The diagnostic order could not be found.");requirePermission(c,order.type==="LABORATORY"?"laboratory.orders.manage":"radiology.orders.manage");if(!["ORDERED","ACCEPTED"].includes(order.status))throw new WonFlowApiError(409,"diagnostic-order-not-startable","Only ordered or accepted work can move into processing.");return database.diagnosticOrder.update({where:{id:order.id},data:{status:"IN_PROGRESS"}});}
async saveResult(rc:WonFlowRequestContext,orderId:string,input:{resultId?:string;resultData?:object;reportText?:string;critical?:boolean;criticalNotes?:string;version?:number}){const c=requireTenantContext(rc),order=await database.diagnosticOrder.findFirst({where:{id:orderId,tenantId:c.tenantId,branchId:requireBranchId(c)}});if(!order)throw new WonFlowApiError(404,"diagnostic-order-not-found","The diagnostic order could not be found.");requirePermission(c,order.type==="LABORATORY"?"laboratory.results.manage":"radiology.reports.manage");if(input.critical&&!input.criticalNotes?.trim())throw new WonFlowApiError(400,"critical-notes-required","Describe why this result is critical.");if(input.resultId){const updated=await database.diagnosticResult.updateMany({where:{id:input.resultId,tenantId:c.tenantId,orderId:order.id,status:"PRELIMINARY",version:input.version},data:{resultData:input.resultData,reportText:input.reportText??null,critical:input.critical??false,criticalNotes:input.criticalNotes??null,performedByMembershipId:c.membershipId,version:{increment:1}}});if(updated.count!==1)throw new WonFlowApiError(409,"diagnostic-result-conflict","The result changed in another session.");return database.diagnosticResult.findUnique({where:{id:input.resultId}});}const created=await database.diagnosticResult.create({data:{tenantId:c.tenantId,orderId:order.id,resultData:input.resultData,reportText:input.reportText??null,critical:input.critical??false,criticalNotes:input.criticalNotes??null,performedByMembershipId:c.membershipId}});if(order.status!=="IN_PROGRESS")await database.diagnosticOrder.update({where:{id:order.id},data:{status:"IN_PROGRESS"}});return created;}
/** Released results for the clinician who ordered them, newest first. */
async getClinicianResults(rc:WonFlowRequestContext,input:{type:"LABORATORY"|"RADIOLOGY"}){const c=requireTenantContext(rc);requirePermission(c,input.type==="LABORATORY"?"laboratory.orders.read":"radiology.orders.read");const orders=await database.diagnosticOrder.findMany({where:{tenantId:c.tenantId,type:input.type,orderedByMembershipId:c.membershipId??undefined,results:{some:{status:{in:["FINAL","AMENDED","CORRECTED"]},releasedAt:{not:null}}}},include:{patient:true,results:{where:{status:{in:["FINAL","AMENDED","CORRECTED"]},releasedAt:{not:null}}}},orderBy:{completedAt:"desc"},take:100});return this.decorate(orders,await this.getDeliveries(c.tenantId,orders.flatMap(order=>order.results.map(result=>result.id))));}
/** Record that the ordering clinician has seen a released result. */
async acknowledgeResult(rc:WonFlowRequestContext,orderId:string,resultId:string){const c=requireTenantContext(rc),order=await database.diagnosticOrder.findFirst({where:{id:orderId,tenantId:c.tenantId}});if(!order)throw new WonFlowApiError(404,"diagnostic-order-not-found","The diagnostic order could not be found.");requirePermission(c,order.type==="LABORATORY"?"laboratory.orders.read":"radiology.orders.read");const result=await database.diagnosticResult.findFirst({where:{id:resultId,tenantId:c.tenantId,orderId:order.id,releasedAt:{not:null}}});if(!result)throw new WonFlowApiError(409,"result-not-acknowledgeable","Only a released result can be acknowledged.");if(result.acknowledgedAt)return result;return database.$transaction(async tx=>{const acknowledged=await tx.diagnosticResult.update({where:{id:result.id},data:{acknowledgedAt:new Date()}});await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId:order.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:"diagnostic.result.acknowledged",entityType:"diagnostic-result",entityId:acknowledged.id,severity:acknowledged.critical?"CRITICAL":"INFORMATION",sourceApplication:c.sourceApplication}});return acknowledged;});}
async releaseResult(rc:WonFlowRequestContext,orderId:string,resultId:string){const c=requireTenantContext(rc),order=await database.diagnosticOrder.findFirst({where:{id:orderId,tenantId:c.tenantId,branchId:requireBranchId(c)}});if(!order)throw new WonFlowApiError(404,"diagnostic-order-not-found","The diagnostic order could not be found.");requirePermission(c,order.type==="LABORATORY"?"laboratory.results.release":"radiology.reports.release");const orderingMembership=await database.tenantMembership.findFirst({where:{id:order.orderedByMembershipId,tenantId:c.tenantId},select:{identityId:true}});return database.$transaction(async tx=>{const result=await tx.diagnosticResult.findFirst({where:{id:resultId,tenantId:c.tenantId,orderId:order.id,status:"PRELIMINARY"}});if(!result)throw new WonFlowApiError(409,"result-not-releasable","The result cannot be released.");const released=await tx.diagnosticResult.update({where:{id:result.id},data:{status:"FINAL",verifiedByMembershipId:c.membershipId,releasedByMembershipId:c.membershipId,verifiedAt:new Date(),releasedAt:new Date()}});await tx.diagnosticOrder.update({where:{id:order.id},data:{status:"COMPLETED",completedAt:new Date()}});const payload={resultId:released.id,orderId:order.id,patientId:order.patientId,orderName:order.name,critical:released.critical};
// Delivery receipts. The patient portal reads released results directly; these
// rows are what proves the result was pushed to each audience and let the
// laboratory show "sent to patient" and "sent to doctor".
await tx.notification.create({data:{tenantId:c.tenantId,patientId:order.patientId,channel:"IN_APP",status:"SENT",templateCode:PATIENT_RESULT_TEMPLATE,sentAt:new Date(),payload}});
if(orderingMembership?.identityId)await tx.notification.create({data:{tenantId:c.tenantId,identityId:orderingMembership.identityId,channel:"IN_APP",status:"SENT",templateCode:CLINICIAN_RESULT_TEMPLATE,sentAt:new Date(),payload}});
await tx.auditEvent.create({data:{tenantId:c.tenantId,branchId:order.branchId,actorMembershipId:c.membershipId,sessionId:c.sessionId,requestId:c.requestId,action:order.type==="LABORATORY"?"laboratory.result.released":"radiology.report.released",entityType:"diagnostic-result",entityId:released.id,severity:released.critical?"CRITICAL":"INFORMATION",sourceApplication:c.sourceApplication}});await tx.outboxEvent.create({data:{tenantId:c.tenantId,type:"diagnostic.result.released",aggregateType:"diagnostic-result",aggregateId:released.id,payload}});return{...released,delivery:{patient:true,clinician:Boolean(orderingMembership?.identityId)}};});}
}export const diagnosticsService=new DiagnosticsService();
