"use client";

import { useCallback, useEffect, useState } from "react";

interface DocumentItem { id: string; title: string; category: string; status: string; createdAt: string; object: { contentType: string; sizeBytes: string } }

export default function PatientDocumentsPage() {
  const [documents, setDocuments] = useState<DocumentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/v1/patient/documents", { cache: "no-store" }); const body = await response.json() as { documents?: DocumentItem[]; error?: string }; if (!response.ok) throw new Error(body.error); setDocuments(body.documents ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Documents could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/v1/patient/documents", { method: "POST", body: new FormData(event.currentTarget) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error); event.currentTarget.reset(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "The document could not be uploaded."); } finally { setBusy(false); } }
  return <div className="space-y-5"><header className="rounded-3xl bg-gradient-to-r from-indigo-700 via-violet-700 to-fuchsia-700 p-6 text-white"><p className="text-xs font-black uppercase tracking-[0.2em] text-violet-100">Patient portal</p><h1 className="mt-2 text-3xl font-black">My health documents</h1><p className="mt-2 text-sm text-violet-100">Upload reports and supporting medical records for your authorized care team.</p></header>
    {error ? <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div> : null}
    <form className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2" onSubmit={(event) => void upload(event)}><div className="md:col-span-2"><h2 className="text-lg font-black">Upload a report</h2><p className="text-xs text-slate-500">PDF, JPG, PNG or WebP · maximum 10 MB</p></div><label className="text-xs font-bold">Document title<input className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2" name="title" placeholder="e.g. Previous laboratory report" required /></label><label className="text-xs font-bold">Category<select className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2" name="category"><option value="LABORATORY_REPORT">Laboratory report</option><option value="RADIOLOGY_REPORT">Radiology report</option><option value="PRESCRIPTION">Prescription</option><option value="DISCHARGE_SUMMARY">Discharge summary</option><option value="OTHER_MEDICAL_RECORD">Other medical record</option></select></label><input accept="application/pdf,image/jpeg,image/png,image/webp" className="md:col-span-2 rounded-xl border border-dashed border-indigo-300 bg-indigo-50 p-4" name="file" required type="file" /><button className="rounded-xl bg-indigo-700 px-5 py-3 text-sm font-black text-white disabled:opacity-50 md:col-span-2" disabled={busy} type="submit">{busy ? "Uploading securely…" : "Upload document"}</button></form>
    <section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Document history</h2>{loading ? <p className="mt-4 text-sm text-slate-500">Loading…</p> : documents.length ? <div className="mt-4 space-y-3">{documents.map((document) => <article className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-100 p-4" key={document.id}><div><div className="font-black">{document.title}</div><div className="text-xs text-slate-500">{document.category.replaceAll("_", " ")} · {document.status} · {new Date(document.createdAt).toLocaleDateString("en-PK")}</div></div><a className="rounded-xl border border-indigo-200 px-4 py-2 text-sm font-bold text-indigo-700" href={`/api/v1/patient/documents/${document.id}`} rel="noreferrer" target="_blank">Open</a></article>)}</div> : <p className="mt-4 rounded-2xl border border-dashed p-8 text-center text-sm text-slate-500">No documents uploaded yet.</p>}</section>
  </div>;
}
